package br.com.alturionx.leadrecall.evento.enums;

public enum Tipo {

    MENSAGEM_RECEBIDA("MENSAGEM_RECEBIDA"),

    LEAD_CRIADO("LEAD_CRIADO"),
    LEAD_ATUALIZADO("LEAD_ATUALIZADO"),

    VEICULO_CRIADO("VEICULO_CRIADO"),
    VEICULO_ATUALIZADO("VEICULO_ATUALIZADO"),

    MATCHING_INICIADO("MATCHING_INICIADO"),
    MATCHING_FINALIZADO("MATCHING_FINALIZADO"),

    OPORTUNIDADE_IDENTIFICADA("OPORTUNIDADE_IDENTIFICADA"),
    OPORTUNIDADE_CRIADA("OPORTUNIDADE_CRIADA"),
    OPORTUNIDADE_ATUALIZADA("OPORTUNIDADE_ATUALIZADA"),

    NOTIFICACAO_CRIADA("NOTIFICACAO_CRIADA"),
    NOTIFICACAO_ENVIADA("NOTIFICACAO_ENVIADA");

    Tipo(String string) {

    }


}